engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 3bc56d141a551d919ec3d9f48d27dab5
ratings:
  paths:
    - "**.rb"
exclude_paths:
  - "config.ru"
  - "config/*"
  - "config/**/*"
  - ".codeclimate.yml"
  - ".rubocop.yml"
  - ".gitignore"
  - "db/*"
  - "db/**/*"
  - "bin/*"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "Capfile"
  - "Guardfile"
  - "*.md"
  - "app/assets/**/*"
  - "app/pdfs/*"
  - "app/inputs/*"
  - "spec/*"
  - "spec/**/*"
