language: ruby
rvm:
  - 2.2.5
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rspec spec
