language: ruby
rvm:
  - 2.2.5
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rspec spec
addons:
  code_climate:
    repo_token: 54177501340cf59d00dbb6734a742dedf611695d65546af8d8449f5c20407429
